def generator(f):
    print('generated by generator')
    def generated(*args, **kwargs):
        print('called generated')
        return f(*args, **kwargs)
    return generated

def generator_lambda(f):
    print('generated by generator_lambda')
    return lambda *args, **kwargs: f(*args, **kwargs)

def func(a, b):
    return a * b

generated_func = generator(func)
generator_func_lambda = generator_lambda(func)

print(func(2, 3))
print(generated_func(4, 5))
print(generator_func_lambda(6, 7))